export const CHARACTERS = [
  {
    name: "Jabala",
    img: "images/jabala.svg",
    hairColor: "hidden",
    eyeColor: "hidden",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: true,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },
  {
    name: "Jack",
    img: "images/jack.svg",
    hairColor: "hidden",
    eyeColor: "blue",
    glasses: false,
    necklace: false,
    earrings: false,
    headCover: true,
    smoker: false,
    facialHair: true,
    buttonShirt: false,
  },
  {
    name: "Jacques",
    img: "images/jacques.svg",
    hairColor: "grey",
    eyeColor: "blue",
    glasses: false,
    necklace: false,
    earrings: false,
    headCover: true,
    smoker: true,
    facialHair: true,
    buttonShirt: false,
  },
  {
    name: "Jai",
    img: "images/jai.svg",
    hairColor: "black",
    eyeColor: "brown",
    glasses: false,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: true,
  },
  {
    name: "Jake",
    img: "images/jake.svg",
    hairColor: "yellow",
    eyeColor: "green",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: true,
  },
  {
    name: "James",
    img: "images/james.svg",
    hairColor: "brown",
    eyeColor: "green",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: true,
    buttonShirt: false,
  },
  {
    name: "Jana",
    img: "images/jana.svg",
    hairColor: "black",
    eyeColor: "hidden",
    glasses: true,
    necklace: true,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: true,
  },
  {
    name: "Jane",
    img: "images/jane.svg",
    hairColor: "yellow",
    eyeColor: "hidden",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },
  {
    name: "Jaqueline",
    img: "images/jaqueline.svg",
    hairColor: "orange",
    eyeColor: "green",
    glasses: true,
    necklace: true,
    earrings: true,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },

  {
    name: "Jazebelle",
    img: "images/jazebelle.svg",
    hairColor: "purple",
    eyeColor: "hidden",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: true,
    facialHair: false,
    buttonShirt: false,
  },
  {
    name: "Jean",
    img: "images/jean.svg",
    hairColor: "brown",
    eyeColor: "blue",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: true,
    smoker: true,
    facialHair: true,
    buttonShirt: false,
  },
  {
    name: "Jeane",
    img: "images/jeane.svg",
    hairColor: "brown",
    eyeColor: "green",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },
  {
    name: "Jed",
    img: "images/jed.svg",
    hairColor: "orange",
    eyeColor: "green",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: true,
    smoker: true,
    facialHair: true,
    buttonShirt: false,
  },
  {
    name: "Jenni",
    img: "images/jenni.svg",
    hairColor: "white",
    eyeColor: "hidden",
    glasses: false,
    necklace: false,
    earrings: false,
    headCover: true,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },
  {
    name: "Jeri",
    img: "images/jeri.svg",
    hairColor: "orange",
    eyeColor: "green",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },
  {
    name: "Jerry",
    img: "images/jerry.svg",
    hairColor: "hidden",
    eyeColor: "blue",
    glasses: false,
    necklace: false,
    earrings: false,
    headCover: true,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },
  {
    name: "Jess",
    img: "images/jess.svg",
    hairColor: "black",
    eyeColor: "blue",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },
  {
    name: "Jocelyn",
    img: "images/jocelyn.svg",
    hairColor: "black",
    eyeColor: "brown",
    glasses: true,
    necklace: false,
    earrings: true,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },
  {
    name: "Jon",
    img: "images/jon.svg",
    hairColor: "brown",
    eyeColor: "green",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: true,
  },
  {
    name: "Jordan",
    img: "images/jordan.svg",
    hairColor: "yellow",
    eyeColor: "hidden",
    glasses: true,
    necklace: true,
    earrings: false,
    headCover: true,
    smoker: false,
    facialHair: false,
    buttonShirt: true,
  },
  {
    name: "Josephine",
    img: "images/josephine.svg",
    hairColor: "grey",
    eyeColor: "brown",
    glasses: false,
    necklace: false,
    earrings: true,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },
  {
    name: "Josh",
    img: "images/josh.svg",
    hairColor: "yellow",
    eyeColor: "green",
    glasses: false,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: false,
    buttonShirt: true,
  },
  {
    name: "Jude",
    img: "images/jude.svg",
    hairColor: "black",
    eyeColor: "green",
    glasses: false,
    necklace: false,
    earrings: false,
    headCover: false,
    smoker: false,
    facialHair: true,
    buttonShirt: true,
  },
  {
    name: "Julie",
    img: "images/julie.svg",
    hairColor: "black",
    eyeColor: "brown",
    glasses: true,
    necklace: false,
    earrings: false,
    headCover: true,
    smoker: false,
    facialHair: false,
    buttonShirt: false,
  },
];
